version: '3.0'
services:
    web:
        image: ssebastijan/magento2:2.4.4
        container_name: magento-2-web
        ports:
            - "9007:80"
        links:
            - db
        volumes:
            - magento-data:/var/www/html
        env_file:
            - env
        networks:
            - magento_network

    db:
        image: mysql:latest
        container_name: magento-2-database
        volumes:
            - db-data:/var/lib/mysql
        env_file:
            - env
        networks:
            - magento_network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: magento-2-phpmyadmin
        ports:
            - "9008:80"
        links:
            - db

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
        container_name: magento-2-elasticsearch
        networks:
            - magento_network
        environment:
            - xpack.security.enabled=false
            - discovery.type=single-node
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
        restart: on-failure

volumes:
    elasticsearch-data:
    magento-data:
    db-data:

networks:
    magento_network:
